# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170830_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpostspage',
            name='page_ptr',
        ),
    ]
