# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:26
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170901_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(to='home.Category'),
        ),
    ]
