# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0006_auto_20170904_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostspage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
