# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170904_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 4, 14, 29, 40, 529850)),
        ),
    ]
