# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170904_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_title_short',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
